export const ADD_ARTICLE = "ADD_ARTICLE";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const CHECKOUT = "CHECKOUT";
export const ADD = "ADD";
export const SUBSTRACT = "SUBSTRACT";
export const SEARCH_ITEM = "SEARCH_ITEM";
export const SET_TERM = "SET_TERM";
export const CLEAR = "CLEAR";

// API
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const GET_PROMOTED_SUCCESS = "GET_PROMOTED_SUCCESS";
export const GET_PROMOTED_FAILURE = "GET_PROMOTED_FAILURE";
export const GET_PURCHASES_SUCCESS = "GET_PURCHASES_SUCCESS";
export const GET_PURCHASES_FAILURE = "GET_PURCHASES_FAILURE";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";
